<div id="portlet_{{portlet.id}}" class="{{parm['width']}}" > 
              <!-- START PANEL -->
              <div class="panel panel">
                <div class="panel-heading ">
                  <div class="panel-title">{{parm['title']}}
                  </div>
                  <div class="panel-controls">
                    <ul>
<li>
<a class="portlet-collapse" data-toggle="collapse"><i class="pg-arrow_maximize"></i></a>
                      </li>
                      <li>
<a href="#" class="portlet-refresh" data-toggle="refresh"><i class="pg-refresh_new"></i></a>
                      </li>
                      <li>
<a href="#" class="portlet-close" data-toggle="close"><i class="pg-close"></i></a>
                      </li>
                    </ul>
</div>
                </div>
                <div class="panel-body">
                    
                    <?php $tabs = explode(',', $parm['tabs']) ?><!-- Nav tabs --><ul class="nav nav-tabs nav-tabs-linetriangle">
                        {% for key,tab in tabs %}
                        <li class="{% if key == 0 %}active{% endif  %}">
                        <a onclick="tabchange()" data-toggle="tab" href="#tab-{{ tab }}"><span>{{ tab }}</span></a>
                        </li>
                        {% endfor %}
                    </ul>
<!-- Tab panes --><div class="tab-content no-padding">
                        
                         {% for key,tab in tabs %}
                        <div class="tab-pane {% if key == 0 %}active{% endif  %}" id="tab-{{ key }}">
                       {{region[key]}}
                      </div>
                        {% endfor %}
                    </div>
   
                </div>
              </div>
              <!-- END PANEL -->{{ content() }}</div>