<div id="widget_{{widget.id}}"class="col-md-{{parm['width']}}" > {{controls}}
<select id="w_{{widget.id}}" style="width:100%" class="input" multiple placeholder="{{parm['title']}}">
     {% for entry in parm['db'] %}
      <option value="{{entry['link_column']}}">{{entry['values']}}</option>
    {% endfor  %}
</select><script>

$("#w_{{widget.id}}").select2();

        $("#w_{{widget.id}}").change(function() {
        
            update_dashboard("{{parm['target_link']}}", $("#w_{{widget.id}}").select2("val"),{{widget.id}});
  
        });



</script>{{ content() }}</div>