<div id="widget_{{widget.id}}"  >{{controls}}   <h3>{{parm['title']}}</h3>
 <div id="w_{{widget.id}}" style="width:100% margin: 0"></div>

<script>

dataIn=
Morris.Donut({
  element: 'w_{{widget.id}}',
   colors: {{parm['colors']}}
    ,
  data:[
  {% for row in parm['db'] %}
{
     label: '{{ row['label']|escape_js }}',
     value: {{ row['value']|escape_js }}
},
{% endfor  %}
]}).on('click', function(i, row){

     update_dashboard("{{parm['link_table']}}","{{parm['target_link']}}","=", row.label,{{widget.id}});
});
</script>{{ content() }}</div>