<div id="widget_{{widget.id}}"   > {{controls}}<style>
#w_{{widget.id}} .ui-selecting.item_{{widget.id}} { background: #FECA40; }
  #w_{{widget.id}} .ui-selected.item_{{widget.id}} { background: #F39814; color: white; }
</style>

<div>
    
    <?php  $max =array();  ?>
    
    {% for entry in parm['db'] %}
    
         <?php  $max[] = $entry['value']; ?>

{% endfor  %}
    
    <?php 
    if(max($max)>0) 
    { 
    $max=max($max);
    }
    else
    {
    $max=1;
    }
    ?>
    

                <div class="widget-progress-bar">
                  <div id="scroll_{{widget.id}}" style="height:{{parm['height']}};">
                      <div id="w_{{widget.id}}">
                {% for entry in parm['db'] %}
                    <div class="item_{{widget.id}}" data-link="{{entry['label']}}" style="padding:10px">
                    <div class="clearfix" >
                      <div class="title">{{entry['label']}}</div>
                      <div class="number"><?php echo round($entry['value']) ?></div>
                    </div>
                    <div class="progress">
                      <div class="progress-bar progress-bar-primary stat1" data-transitiongoal="82" aria-valuenow="82" style="width: {{(entry['value']*100) / max }}%;"></div>
                    </div>
                    </div> 
                    
                {% endfor  %}
                 </div>
                  </div>
                </div>
                      
</div>
</div>
  <script>
  $(function() {
    $( "#w_{{widget.id}}" ).selectable({
      stop: function() {
        var link_set=[];
        $( "div.ui-selected.item_{{widget.id}}", this ).each(function() {
            link_set.push($(this).data('link'));
        });
        
     update_dashboard("{{parm['link_table']}}","{{parm['target_link']}}","=", link_set,{{widget.id}});
        
        
      }
    });
        $("#scroll_{{widget.id}}").mCustomScrollbar();
  });
  
  </script>
  
{{ content() }}</div>