<div id="portlet_{{portlet.id}}" class="{{parm['width']}}" class=" sm-no-padding" > 
                  <div class="panel panel-transparent" style="background-color:{{parm['color']}}">
                    <div class="panel-body no-padding">
                      <div id="portlet-advance" class="panel panel-default">
                        <div class="panel-heading ">
                          <div class="panel-title">{{parm['title']}}
                          </div>
                          <div class="panel-controls">
                            <ul>
<li>
<a href="#" class="portlet-collapse" data-toggle="collapse"><i class="portlet-icon portlet-icon-collapse"></i></a>
                              </li>
                              <li>
<a href="#" class="portlet-maximize" data-toggle="maximize"><i class="portlet-icon portlet-icon-maximize"></i></a>
                              </li>
                              <li>
<a href="#" class="portlet-close" data-toggle="close"><i class="portlet-icon portlet-icon-close"></i></a>
                              </li>
                            </ul>
</div>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                            {{region[0]}}
                            </div>
                            <div class="row">
                            {{region[1]}}
                            </div>
                            <div class="row">
                            {{region[2]}}
                            </div>

                          </div>
                        </div>
                      </div>
                    </div>
                  {{ content() }}</div>