
	<div id="<?php echo "w_".$widget->id ?>" >
  </div>


  <div id="sliders">
	<table>
		<tr><td>Alpha Angle</td><td><input id="<?php echo "R0".$widget->id ?>" type="range" min="0" max="45" value="15"/> <span id="<?php echo "R0".$widget->id."-value" ?>" class="value"></span></td></tr>
	    <tr><td>Beta Angle</td><td><input id="<?php echo "R1".$widget->id ?>" type="range" min="0" max="45" value="15"/> <span id="<?php echo "R1".$widget->id."-value" ?>" class="value"></span></td></tr>
	</table>
</div>

  <?php 

  function transpose($arr,$type) {
	$out = array();
    foreach ($arr as $key => $subarr) {
    	foreach ($subarr as $subkey => $subvalue) {
		if($subkey!='x_axis'){
			if($type == "date")
			{
    		$out[$subkey][$key] = "[Date.parse('".$subarr['x_axis']."') , ".$subvalue."]" ;
			}
			else
			{
			$out[$subkey][$key] = "[".$subarr['x_axis']." , ".$subvalue."]" ;
			}
			}
    	}
    }
    return $out;
}
  $dataOut = transpose($data['db']['hc_table1'], $data['parm']['x_type'] );

  $out = array();
  foreach ($dataOut as $key => $subarr) {
  $out[]= "{ name: '".$key."', data: [ ".join($subarr, ',')."]}";
		}
 ?>

<script>
  $(function () {
  var <?php echo "chart_".$widget->id ?> = new Highcharts.Chart({
        chart: {
			renderTo: '<?php echo "w_".$widget->id ?>',
            type: 'column',
			options3d: {
                enabled: true,
                alpha: 15,
                beta: 15,
                depth: 50,
                viewDistance: 25
            }
			},
			  credits: {
  enabled: false
  },
		colors: <?php echo $data['parm']['color_scheme'] ?>,
        title: {
            text: '<?php echo $data['parm']['title'] ?>'
        },
        subtitle: {
            text: '<?php echo $data['parm']['subtitle'] ?>'
        },
        xAxis: {
		title: {
                text: '<?php echo $data['parm']['x_label'] ?>'
            },
		<?php if($data['parm']['x_type'] =="date")
			{
	echo "type: 'datetime',
	";
			}
			?>
			allowDecimals: true
        },
        yAxis: {
            title: {
                text: '<?php echo $data['parm']['y_label'] ?>'
            }
            },
        tooltip: {
            pointFormat: '{series.name}<b></br>{point.y}<b><br>'
        },
        plotOptions: {
            column: {
                depth: 25
            }
        },
        series: [<?php echo join($out, ',') ?>],

    });


	function showValues<?php echo "_".$widget->id ?>() {
        $('#<?php echo "R0".$widget->id."-value" ?>').html(chart<?php echo "_".$widget->id ?>.options.chart.options3d.alpha);
        $('#<?php echo "R1".$widget->id."-value" ?>').html(chart<?php echo "_".$widget->id ?>.options.chart.options3d.beta);
    }

    // Activate the sliders
    $('#<?php echo "R0".$widget->id ?>').on('change', function () {
        chart<?php echo "_".$widget->id ?>.options.chart.options3d.alpha = this.value;
        showValues<?php echo "_".$widget->id ?>();
        chart<?php echo "_".$widget->id ?>.redraw(false);
    });
    $('#<?php echo "R1".$widget->id ?>').on('change', function () {
        chart<?php echo "_".$widget->id ?>.options.chart.options3d.beta = this.value;
        showValues<?php echo "_".$widget->id ?>();
        chart<?php echo "_".$widget->id ?>.redraw(false);
    });

    showValues<?php echo "_".$widget->id ?>();


});

  
</script>



