<div id="widget_{{widget.id}}"  class="{{parm['width']}}" > {{controls}}

<div>
    
    <?php  $max =array();  ?>
    
    {% for entry in parm['db'] %}
    
         <?php  $max[] = $entry['value']; ?>

{% endfor  %}
    
    <?php 
    if(max($max)>0) 
    { 
    $max=max($max);
    }
    else
    {
    $max=1;
    }
    ?>
    
    <style>
    
    td {
    position: relative;
}
.rowprogress {
    position: absolute;
    left: 0;
    top: 0;
    bottom: 0;
    background-color: green;
     opacity: 0.2;
    z-index: 99;
}
</style>

<table id="w_{{widget.id}}" class="table table-hover">
    <thead>
                          <tr>
                              <th>Please Select </th>
                              </tr>
                        </thead>
    <tbody>
{% for entry in parm['db'] %}
 <tr> 
    <td ><div class="rowprogress" style="width:{{(entry['value']*100) / max }}%"></div> {{entry['label']}} </td>
 </tr>
{% endfor  %}
</tbody>
</table>
</div>   <script>
   var initTableWithSearch = function() {
        var table = $('#w_{{widget.id}}');
        
 <?php $linking_column=array(); ?>     
 {% for row in parm['db'] %}
  <?php $linking_column[]=$row['link_column']; ?> 
{% endfor  %}
var linking_column=<?php echo json_encode($linking_column) ?> ;

        var settings = {
            "sDom": 'T<"clear">lfrtip',
            "destroy": true,
            "bLengthChange": false,
            "bFilter": false,
            "bInfo": false,
            "scrollY": "400px",
            "scrollX": true,
            "paging":         false,
                    "oTableTools": {
            "sRowSelect": "multi",
            "aButtons" : []
        }
        };
        


    table.dataTable(settings);
        

         $('#w_{{widget.id}}').on( 'click', 'tr', function () {
        $(this).toggleClass('selected');
            var oTT = TableTools.fnGetInstance( 'w_{{widget.id}}' );
    var aData = oTT.fnGetSelectedIndexes();
    var link_set=[];
    $.each( aData, function( key, value ) {
    link_set.push(linking_column[value]);
    });
    
    
    
    
     update_dashboard("{{parm['target_link']}}", link_set,{{widget.id}});
        
    } );
   
    }
    
    initTableWithSearch();
    
    
    
    
    </script>{{ content() }}</div>