<div id="widget_{{widget.id}}"   > {{controls}}<style>
#w_{{widget.id}} .ui-selecting { background: #FECA40; }
  #w_{{widget.id}} .ui-selected { background: #F39814; color: white; }
</style>

<div>
    
    <?php  $max =array();  ?>
    
    {% for entry in parm['db'] %}
    
         <?php  $max[] = $entry['value']; ?>

{% endfor  %}
    
    <?php 
    if(max($max)>0) 
    { 
    $max=max($max);
    }
    else
    {
    $max=1;
    }
    ?>
    
    <style>
    
    td {
    position: relative;
}
.rowprogress {
    position: absolute;
    left: 0;
    top: 0;
    bottom: 0;
    background-color: green;
     opacity: 0.2;
    z-index: 99;
}
</style>

                <div class="widget-table">
                  <div id="scroll_{{widget.id}}" style="height:400px">
<table class="table table-hover">
    <tbody id="w_{{widget.id}}">
{% for entry in parm['db'] %}
 <tr data-link="{{entry['label']}}"> 
    <td ><div class="rowprogress" style="width:{{(entry['value']*100) / max }}%"></div> {{entry['label']}} </td>
 </tr>
{% endfor  %}
</tbody>
</table>
</div>
</div>
</div>
  <script>
  $(function() {
    $( "#w_{{widget.id}}" ).selectable({
      stop: function() {
        var link_set=[];
        $( "tr.ui-selected", this ).each(function() {
            link_set.push($(this).data('link'));
        });
        
     update_dashboard("{{parm['link_table']}}","{{parm['target_link']}}","=", link_set,{{widget.id}});
        
        
      }
    });
        $("#scroll_{{widget.id}}").mCustomScrollbar();
  });
  
  </script>
  
{{ content() }}</div>