<div class="modal-content">


  <?php echo $this->tag->form("canvas/deleteCanvas") ?>
  
  <?php echo $this->getContent(); ?>

  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <br>
      <i class="fa fa-trash-o fa-7x"></i>
      <h4 id="myModalLabel" class="semi-bold">Canvas Delete Confirmation</h4>
      <p class="no-margin"> Are you sure you want to delete this Canvas. </p>
      <br>
 </div>
  <div class="modal-body">
    


  <div class="modal-footer">
    <?php echo $this->tag->hiddenField("id") ?>
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
    <?php echo $this->tag->submitButton(array("Delete","class"=>"btn btn-primary")) ?>

  </div>

  </form>
</div>