<div id="portlet_{{portlet.id}}" class="{{parm['width']}}" >  <style type="text/css">
.tab-content > .tab-pane,
.pill-content > .pill-pane {
    display: block;     /* undo display:none          */
    height: 0;          /* height:0 is also invisible */ 
    overflow-y: hidden; /* no-overflow                */
}
.tab-content > .active,
.pill-content > .active {
    height: auto;       /* let the content decide it  */
}   
 </style>             <div >
                    <?php $tabs = explode(',', $parm['tabs']) ?>

                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs">
                        {% for key,tab in tabs %}
                        <li class="{% if key == 0 %}active{% endif  %}">
                        <a onclick="tabchange()" data-toggle="tab" href="#tab-<?php echo str_replace (" ","_",$key) ?>"><span>{{ tab }}</span></a>
                        </li>
                        {% endfor %}
                    </ul>
                    <!-- Tab panes -->
                    
                    <div class="tab-content no-padding">
                        
                         {% for key,tab in tabs %}
                        <div class="tab-pane fade {% if key == 0 %}in active{% endif  %}" id="tab-<?php echo str_replace (" ","_",$key) ?>">
                       {{region[key]}}
                      </div>
                        {% endfor %}
                    </div>
   
                </div>

  {{ content() }}</div>