<div id="w_{{widget.id}}" style="width:100%;height:500px"><svg></svg></div><script>
(function() {
    
    var datain=[
{% for key,series in parm['db'] %}
{
     "key": '{{key|escape_js}}',
     "values": [
        {% for row in series %}
    {x:'{{ row['x_axis']|escape_js }}',y:{{ row['value']|escape_js }}} ,
        {% endfor  %}
]},

{% endfor  %}
];
    
                nv.addGraph(function() {
                    var chart = nv.models.scatterChart()

                    d3.select('#w_{{widget.id}} svg')
                        .datum(datain)
                        .transition().duration(500)
                        .call(chart);

                                        nv.utils.windowResize(function() {

                        chart.update();

                        var xTicks = d3.select('.nv-y.nv-axis  g').selectAll('g');
                        xTicks
                            .selectAll('text')
                            .attr('transform', function(d, i, j) {
                                return 'translate (10, 0)'
                            });

                        var yTicks = d3.select('.nv-x.nv-axis  g').selectAll('g');
                        yTicks
                            .selectAll('text')
                            .attr('transform', function(d, i, j) {
                                return 'translate (0, 10)'
                            });

                        var minmax = d3.select('.nv-x.nv-axis g');
                        minmax
                            .selectAll('text')
                            .attr('transform', function(d, i, j) {
                                return 'translate (0, 10)'
                            });


                        var legend = d3.select('.nv-legendWrap .nv-legend');
                        legend.attr('transform', function(d, i, j) {
                            return 'translate (0, -20)'
                        });

                    });

                    $('#w_{{widget.id}}').data('chart', chart);

                    return chart;
                });
            })();


</script>{{ content() }}