<div id="widget_{{widget.id}}" class="{{parm['width']}}" >{{controls}}<div id="w_{{widget.id}}" style="width:100% min-width: 600px; height: 500px; margin: 0 auto"></div><script>
selectedPoints = [];
$('#w_{{widget.id}}').highcharts({
            chart: {
            type: 'pie',
            spacingBottom: 50,
            spacingTop: 50,
            spacingLeft: 50,
            spacingRight: 50,
			zoomType: 'xy'
        },
           plotOptions: {
        series: {
            allowPointSelect: true,
            point: {
                events: {
                    select: function (event) {
                        var chart = this.series.chart;
                        if (event.accumulate) {
                            selectedPoints.push(this);
                        } else {
                            selectedPoints = [this];
                        }
                        var temp=[];
                        $.each(selectedPoints, function (i, value) {
                            temp.push(value.name);
                        });
                        
                             update_dashboard("{{parm['target_link']}}", temp,{{widget.id}});
                    },
                    unselect: function (event) {
                        
                        var index = selectedPoints.indexOf(this);
                        if (index > -1) {
                            selectedPoints.splice(index, 1);
                            var temp=[];
                        $.each(selectedPoints, function (i, value) {
                            temp.push(value.name);
                        });
                            update_dashboard("{{parm['target_link']}}", temp,{{widget.id}});
                        }
                        
                    }
                }
            }
        }
    },
 title: {
            text: '{{parm['chart_title']}}'
        },
        		  credits: {
  enabled: false
  },
    colors:{{parm['colors']}},
  series: [{
     data: [
{% for row in parm['db'] %}
{
     name: '{{ row['label']|escape_js }}',
     y: {{ row['value']|escape_js }}
},
{% endfor  %}
]}]
});
</script>{{ content() }}</div>