<?php echo $this->getContent(); ?>

<ul class="breadcrumb">
  <li>
    <p>YOU ARE HERE</p>
  </li>
  <li>
    <a href="#" class="active">Edit User</a>
  </li>
</ul>
<div class="page-title">
  <i class="icon-custom-left"></i>
  <h3>
    Edit - <span class="semi-bold">User</span>
  </h3>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="tabbable tabs-right">
      <ul class="nav nav-tabs" id="tab-3">
        <li class="active"  style="min-width:250px;">
          <a href="#tab3-1">Basic Information</a>
        </li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="tab3-1" >
          <div class="col-md-12">
            <?php echo $this->tag->form(array("users/save")) ?>
            <div class="row column-seperation">

              <div class="col-md-4" style="min-height:500px;">
                <h3>
                  <span class="semi-bold">Basic</span> Information
                </h3>
              </div>
              <div class="col-md-8">
                <div class="grid-body no-border">
                  <br>

                    <div class="form-group">
                      <label class="form-label">Email</label>
                      <span class="help">e.g. "User@primeanalytics.io"</span>
                      <div class="input-with-icon  right">
                        <i class=""></i>
                        <?php echo $this->tag->textField(array("email", "class" => "form-control")) ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="form-label">Full Name</label>
                      <span class="help">e.g. "John Doe"</span>
                      <div class="input-with-icon  right">
                        <i class=""></i>
                        <?php echo $this->tag->textField(array("full_name", "class" => "form-control")) ?>
                      </div>
                    </div>
                    
                    <div class="form-group">
                      <label class="form-label">Profile Picture</label>
                      <span class="help">e.g. "Please select"</span>
                      <div class="input-with-icon  right">
                        <i class=""></i>
                        <?php echo $this->tag->textField(array("image_path", "class" => "form-control")) ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="form-label">Password</label>
                      <div class="input-with-icon  right">
                        <i class=""></i>
                        <?php echo $this->tag->passwordField(array("password", "class" => "form-control")) ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="form-label">Role</label>
                      <div class="input-with-icon  right">
                        <i class=""></i>
                        <?php echo $this->tag->textField(array("role", "class" => "form-control")) ?>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="form-label">Status</label>
                      <div class="input-with-icon  right">
                        <i class=""></i>
                        <?php echo $this->tag->textField(array("status", "class" => "form-control")) ?>
                      </div>
                    </div>

                    <?php echo $this->tag->hiddenField("organisation_id") ?>
                    
                    <?php echo $this->tag->hiddenField("id") ?>
                  </div>
              </div>
            </div>

            <p class="pull-right">
              <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-success btn-cons")) ?>
              <button type="button" class="btn btn-white btn-cons">Cancel</button>
            </p>
            </form>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>





<div class="row-fluid">
  <div class="span12">
    <div class="grid simple ">
      <div class="grid-title">
        <h4>
          Dashboards
        </h4>
        <div class="tools">
          <a></a>
          <a></a>
          <a href="javascript:;" class="collapse"></a>
          <a href="javascript:;" class="remove"></a>
        </div>

      </div>

      <div class="grid-body ">
        <table class="table table-hover table-condensed">
          <thead>
            <tr>
              <th>Title</th>
              <th>Icon</th>
              <th>Weight</th>
              <th style="width:20%">Actions</th>

            </tr>
          </thead>
          <tbody>
            <?php foreach ($user_dashboards as $dashboard) { ?>
            <tr>
              <td>
                <?php echo $dashboard->title ?>
              </td>
              <td>
                <?php echo $dashboard->icon ?>
              </td>
              <td>
                <?php echo $dashboard->weight ?>
              </td>
              <td>
                <?php echo $this->tag->linkTo(array("Users/disable_dashboard/" . $dashboard->id."/".$email, "Disable",'class'=>"btn btn-warning btn-xs btn-small")); ?>
              </td>
            </tr>
            <?php } ?>
            
            <?php foreach ($dashboards as $dashboard) { ?>
            <tr>
              <td>
                <?php echo $dashboard->title ?>
              </td>
              <td>
                <?php echo $dashboard->icon ?>
              </td>
              <td>
                <?php echo $dashboard->weight ?>
              </td>
              <td>
                <?php echo $this->tag->linkTo(array("Users/enable_dashboard/" . $dashboard->id."/".$email, "Enable",'class'=>"btn btn-success btn-xs btn-small")); ?>
              </td>
            </tr>
            <?php } ?>
            
          </tbody>

        </table>
      </div>
    </div>
  </div>
</div>



