<?php use Phalcon\Tag as Tag ?>

<?php $auth = $this->session->get('auth');?>

<!-- BEGIN HEADER -->
<div class="header navbar navbar-inverse ">
  <!-- BEGIN TOP NAVIGATION BAR -->
  <div class="navbar-inner">
    <div class="header-seperation">
      <ul class="nav pull-left notifcation-center" id="main-menu-toggle-wrapper" style="display:none">
        <li class="dropdown">
          <a id="main-menu-toggle" href="#main-menu"  class="" >
            <div class="iconset top-menu-toggle-white"></div>
          </a>
        </li>
      </ul>
      <!-- BEGIN LOGO -->
      <a onClick="history.go(0)">
        <img  src="/theme/webarch/assets/img/logo.png" class="logo" alt=""  data-src="/theme/webarch/assets/img/logo.png" data-src-retina="/theme/webarch/assets/img/logo2x.png" width="121" height="35"/>
      </a>
      <!-- END LOGO -->

    </div>
    <!-- END RESPONSIVE MENU TOGGLER -->
    <div class="header-quick-nav" >
      <!-- BEGIN TOP NAVIGATION MENU -->
      <div class="pull-left">
        <ul class="nav quick-section">
          <li class="quicklinks">
            <a href="#" class="" id="layout-condensed-toggle" >
              <div class="iconset top-menu-toggle-dark"></div>
            </a>
          </li>
        </ul>
        <ul class="nav quick-section">
          <li class="quicklinks">
            <a onClick="history.go(0)" class="" >
              <div class="iconset top-reload"></div>
            </a>
          </li>
        </ul>
      </div>
      <!-- END TOP NAVIGATION MENU -->
      <!-- BEGIN CHAT TOGGLER -->
      <div class="pull-right">
        <div class="chat-toggler">
          <a href="#" class="dropdown-toggle" id="my-task-list" data-placement="bottom"  data-content='' data-toggle="dropdown" data-original-title="Notifications">
            <div class="user-details">
              <div class="username">
                <span class="badge badge-important">3</span>
                <?php echo $auth['full_name'] ?>
              </div>
            </div>
          </a>

        </div>
        <ul class="nav quick-section ">
          <li class="quicklinks">
            <a data-toggle="dropdown" class="dropdown-toggle  pull-right " href="#" id="user-options">
              <div class="iconset top-settings-dark "></div>
            </a>
            <ul class="dropdown-menu  pull-right" role="menu" aria-labelledby="user-options">
              <li>
                <a href="/session/end">
                  <i class="fa fa-power-off"></i>&nbsp;&nbsp;Log Out
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
      <!-- END CHAT TOGGLER -->
    </div>
    <!-- END TOP NAVIGATION MENU -->

  </div>
  <!-- END TOP NAVIGATION BAR -->
</div>
<!-- END HEADER -->
<!-- BEGIN CONTAINER -->
<div class="page-container row-fluid">
  <!-- BEGIN SIDEBAR -->
  <div class="page-sidebar" id="main-menu">
    <!-- BEGIN MINI-PROFILE -->
    <div class="page-sidebar-wrapper scrollbar-dynamic" id="main-menu-wrapper">
      <div class="user-info-wrapper">
        <div class="user-info">
          <div class="greeting">Welcome</div>
          <div class="username">
            <?php echo $auth['full_name'] ?>
          </div>
          <div class="status">
            Status<a >
              <div class="status-icon green"></div>Online
            </a>
          </div>
        </div>
      </div>
      <!-- END MINI-PROFILE -->

      <!-- BEGIN SIDEBAR MENU -->
      <p class="menu-title">
        BROWSE <span class="pull-right">
          <a onClick="history.go(0)">
            <i class="fa fa-refresh"></i>
          </a>
        </span>
      </p>
      <ul>

        <?php $menu= $this->elements->getMenu();
		foreach($menu as $menuItem)
        { 
				      echo '<li class="">';
        echo Phalcon\Tag::linkTo($menuItem['link'], '<i class="fa '.$menuItem['icon'].'"></i> <span class="title">'.$menuItem['title'].'</span> <span class="selected"></span>');
         echo '</li>';
				
				}

				?>

      </ul>

      <div class="clearfix"></div>
      <!-- END SIDEBAR MENU -->
    </div>
  </div>
  <a href="#" class="scrollup">Scroll</a>
  <div class="footer-widget">
    <div class="pull-right">
      <a href="/session/end">
        <i class="fa fa-power-off"></i>
      </a>
    </div>
  </div>
  <!-- END SIDEBAR -->
  <!-- BEGIN PAGE CONTAINER-->

  <div class="page-content">
    <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <div id="portlet-config" class="modal hide">
      <div class="modal-header">
        <button data-dismiss="modal" class="close" type="button"></button>
        <h3>Widget Settings</h3>
      </div>
      <div class="modal-body"> Widget settings form goes here </div>
    </div>
    <div class="clearfix"></div>
    <div class="overlayer">
      <div class="overlayer-wrapper overlay-fixed">
        <div class="content">
          <h2>
            <?php echo $dashboard->title ?>
          </h2>
          <h4 id ="title" style="background-color:#018EC3;color:#FFFFFF; padding:5px;">
            Please Select Marker <i class="icon-map-marker"></i>
          </h4>
          <?php echo $this->getContent() ?>
        </div>
      </div>
    </div>
    <div id="world-map" class="demo-map" style="height:860px;"></div>
  </div>

</div>
<!-- END CONTAINER -->



<?php echo Tag::javascriptInclude('assets/plugins/jquery-jvectormap/js/jquery-jvectormap-1.2.2.min.js'); ?>
<?php echo Tag::javascriptInclude('assets/plugins/jquery-jvectormap/js/jquery-jvectormap-world-mill-en.js'); ?>
<!-- END PAGE LEVEL PLUGINS -->
<!-- PAGE JS -->


<script>

  var markers = [
  { latLng: [-6.175, 106.8283], name: 'Indonesia (APAC)' },
  { latLng: [37.55, 126.9667], name: 'Korea (APAC)' },
  { latLng: [3.1333, 101.7], name: 'Malaysia (APAC)' },
  { latLng: [-42, 174], name: 'New Zealand (APAC)' },
  { latLng: [13, 122], name: 'Philippines (APAC)' },
  { latLng: [1.3, 103.8], name: 'Singapore (APAC)' },
  { latLng: [13.75, 100.4833], name: 'Thailand (APAC)' },
  { latLng: [21.0333, 105.85], name: 'Vietnam (APAC)' },
  { latLng: [22.2783, 114.1747], name: 'Hong Kong (GRC)' },
  { latLng: [23.5, 121], name: 'Taiwan (GRC)' },
  { latLng: [21, 78], name: 'India SC (India)' },

  { latLng: [42.75, 25.5], name: 'Bulgaria (CEE)' },
  { latLng: [45.8, 16], name: 'Croatia (CEE)' },
  { latLng: [35, 33], name: 'Cyprus (CEE)' },
  { latLng: [49.75, 15.75], name: 'Czech Republic (CEE)' },
  { latLng: [59, 26], name: 'Estonia (CEE)' },
  { latLng: [39, 22], name: 'Greece (CEE)' },
  { latLng: [47.4333, 19.25], name: 'Hungary (CEE)' },
  { latLng: [57, 25], name: 'Latvia (CEE)' },
  { latLng: [55, 24], name: 'Lithuania (CEE)' },
  { latLng: [52.2167, 21.0333], name: 'Poland (CEE)' },
  { latLng: [44.4167, 26.1], name: 'Romania (CEE)' },
  { latLng: [60, 90], name: 'Russia (CEE)' },
  { latLng: [44.8, 20.4667], name: 'Serbia (CEE)' },
  { latLng: [48.15, 17.1167], name: 'Slovakia (CEE)' },
  { latLng: [46.05, 14.5], name: 'Slovenia (CEE)' },
  { latLng: [49, 32], name: 'Ukraine (CEE)' },
  { latLng: [28, 2], name: 'Algeria (MENA)' },
  { latLng: [26.0275, 50.55], name: 'Bahrain (MENA)' },
  { latLng: [26, 30], name: 'Egypt (MENA)' },
  { latLng: [31, 35], name: 'Israel (MENA)' },
  { latLng: [31.95, 35.9333], name: 'Jordan (MENA)' },
  { latLng: [33.9, 35.5333], name: 'Lebanon (MENA)' },
  { latLng: [32, -6], name: 'Morocco (MENA)' },
  { latLng: [33.6667, 73.1667], name: 'Pakistan (MENA)' },
  { latLng: [25.3, 51.5167], name: 'Qatar (MENA)' },
  { latLng: [24, 45], name: 'Saudi Arabia (MENA)' },
  { latLng: [-30, 25], name: 'South Africa (MENA)' },
  { latLng: [34, 9], name: 'Tunisia (MENA)' },
  { latLng: [39.9167, 32.8333], name: 'Turkey (MENA)' },
  { latLng: [24.4667, 54.3667], name: 'United Arab Emirates (MENA)' },
  { latLng: [-30, 25], name: 'South Africa (ZA)' },
  { latLng: [19, -99.1333], name: 'Mexico (Mexico)' },
  { latLng: [-34,-64 ], name: 'Argentina (OLA)' },
  { latLng: [-16.712, -64.666], name: 'Bolivia (OLA)' },
  { latLng: [-33.4333, -70.6667], name: 'Chile (OLA)' },
  { latLng: [4.5833, -74.0667], name: 'Colombia (OLA)' },
  { latLng: [9.9333, -84.0833], name: 'Costa Rica (OLA)' },
  { latLng: [19, -70.6667], name: 'Dominican Republic (OLA)' },
  { latLng: [-0.15, -78.35], name: 'Ecuador (OLA)' },
  { latLng: [13.6667, -89.1667], name: 'El Salvador (OLA)' },
  { latLng: [14.6333, -90.5], name: 'Guatemala (OLA)' },
  { latLng: [14.1, -87.2167], name: 'Honduras (OLA)' },
  { latLng: [8.9667, -79.5333], name: 'Panama (OLA)' },
  { latLng: [-25.2667, -57.6667], name: 'Paraguay (OLA)' },
  { latLng: [-12.0433, -77.0283], name: 'Peru (OLA)' },
  { latLng: [10.6667, -61.5167], name: 'Trinidad & Tobago (OLA)' },
  { latLng: [-34.8833, -56.1667], name: 'Uruguay (OLA)' },
  { latLng: [10.5, -66.9667], name: 'Venezuela (OLA)' },


  ];

  $('#world-map').vectorMap({
  map: 'world_mill_en',
  showTooltip: true,
  scaleColors: ['#C8EEFF', '#0071A4'],
  normalizeFunction: 'polynomial',
  focusOn:{
  x: 0.5,
  y: 0.5,
  scale: 2.5
  },
  zoomMin:0.85,
  hoverColor: false,
  regionStyle:{
  initial: {
  fill: '#99CCFF',
  "fill-opacity": 1,
  stroke: '#babdc0',
  "stroke-width": 0,
  "stroke-opacity": 0
  },
  hover: {
  "fill-opacity": 0.8
  },
  selected: {
  fill: 'yellow'
  },
  selectedHover: {
  }
  },
  markerStyle: {
  initial: {
  fill: '#f35958',
  stroke: '#f35958',
  "fill-opacity": 1,
  "stroke-width": 4,
  "stroke-opacity": 5,
  r: 5
  },
  markersSelectable: true,
  selected: {
  fill: 'blue'
  },
  hover: {
  stroke: 'black',
  "stroke-width": 2
  },
  selectedMarkers:[1
  ],
  selected: {
  fill: 'blue'
  },
  selectedHover: {
  }
  },
  backgroundColor: '#FCFEFF',
  markers: markers,

  onMarkerOver:function(event, index){
  $("#title").html(markers[index].name);
  },

  onMarkerClick:function(event, index){

  $(location).attr('href', markers[index].name);
  }
  });
</script>
