
  <div id="<?php echo "w_".$widget->id ?>" >
  </div>

  <?php 

  function transpose($arr,$type) {
	$out = array();
    foreach ($arr as $key => $subarr) {
    	foreach ($subarr as $subkey => $subvalue) {
		if($subkey!='x_axis'){
			if($type == "date")
			{
    		$out[$subkey][$key] = "[Date.parse('".$subarr['x_axis']."') , ".$subvalue."]" ;
			}
			else
			{
			$out[$subkey][$key] = "[".$subarr['x_axis']." , ".$subvalue."]" ;
			}
			}
    	}
    }
    return $out;
}
  $dataOut = transpose($data['db']['hc_table1'], $data['parm']['x_type'] );

  $out = array();
  foreach ($dataOut as $key => $subarr) {
  $out[]= "{ name: '".$key."', data: [ ".join($subarr, ',')."]}";
		}
 ?>

<script>
  $(function () {
    $('#<?php echo "w_".$widget->id ?>').highcharts({
        chart: {
            type: 'area'
			},
		colors: <?php echo $data['parm']['color_scheme'] ?>,
        title: {
            text: '<?php echo $data['parm']['title'] ?>'
        },
        subtitle: {
            text: '<?php echo $data['parm']['subtitle'] ?>'
        },
        xAxis: {
		title: {
                text: '<?php echo $data['parm']['x_label'] ?>'
            },
		<?php if($data['parm']['x_type'] =="date")
			{
	echo "type: 'datetime',
	";
			}
			?>
			allowDecimals: true
        },
        yAxis: {
            title: {
                text: '<?php echo $data['parm']['y_label'] ?>'
            }
            },
        tooltip: {
            pointFormat: '{series.name}<b>{point.y}<b><br>'
        },
        plotOptions: {
            area: {
                marker: {
                    enabled: false,
                    symbol: 'circle',
                    radius: 2,
                    states: {
                        hover: {
                            enabled: true
                        }
                    }
                }
            }
        },
        series: [<?php echo join($out, ',') ?>],

    });
});

  
</script>






