  <div id="demo"></div>

  <script>

    var dataSet = [
    <?php 
    
    $out = array();
    $link_array=array();
    
      foreach ($data['db']['table1'] as $key => $subarr) 
      {
      $newarr=array();
            foreach($subarr as $sub_key=>$sub_value)
                                {
                                 if($sub_key!="widget_link_column")
                                 {
                                    $floatVal = floatval($sub_value);
                                    // If the parsing succeeded and the value is not equivalent to an int
                                    if($floatVal && intval($floatVal) != $floatVal)
                                    {
                                    $newarr[]= number_format ( $sub_value , 2 , "." , "," );
                                    }
                                    else
                                    {
                                    $newarr[]=$sub_value;
                                    }
                                 }
                                
                                else
                                {
                                $link_array[]=$sub_value;
                                };
                                }

      $out[]= "['".implode("','" , $newarr)."']";
      }
      echo implode(",",$out);
      ?>
    ];

    $(document).ready(function() {
    $('#demo').html( '<table cellpadding="0" cellspacing="0" border="0" class="display" id="example"></table>' );

    $('#example').dataTable( {
    "data": dataSet,
    "columns": [
    <?php 
    
    $out = array();
    
      foreach (array_keys($data['db']['table1']['0']) as $key) 
      {
       if($key!="widget_link_column")
       {
      $out[]= "{ \"title\": \"".$key."\"}";
      }
      }
      echo implode(",",$out);
      ?>

    ]
    } );

    var table = $('#example').DataTable();

    $('#example tbody').on('click', 'tr', function () {
    var link_array=<?php echo json_encode($link_array)?>;
    
    var name = link_array[table.row( this ).index()];

    var link= '[{"name":"<?php echo $data['link']['table1'] ?>","value":"'+name+'"}]';

    $(location).attr('href','/dashboard/render/<?php echo $data['dashboard_link']['table1'] ?>/dashboard/'+ link);

    } );

    } );
    

  </script>




