<div class="modal-content">
  
  <?php echo $this->tag->form("widget/save") ?>

  <?php echo $this->getContent(); ?>

  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <br>
      <i class="fa fa-arrows-alt fa-7x"></i>
      <h4 id="myModalLabel" class="semi-bold">Widget Move Confirmation</h4>
      <p class="no-margin"> Are you sure you want to move this widget. </p>
      <br>
 </div>
  <div class="modal-body">

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <?php echo $this->tag->submitButton(array("Move","class"=>"btn btn-primary")) ?>

  </div>

  </form>
</div>