<div class="modal-content">
    <?php echo $this->getContent(); ?>
    <form method="post" action="{{form_type}}">
    <div class="modal-header">
        <h4 id="myModalLabel" class="semi-bold">Create New {{type}}.</h4>
        <p class="no-margin">Please provide all the required information. </p>
    </div>
    <div class="modal-body">
{{form_body}}
    </div>
    <div class="modal-footer bg-blue">   
        {{ hidden_field("column")}}
        {{ hidden_field("row")}}
        {{ hidden_field("portlet_id")}}
        <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
        <?php echo $this->tag->submitButton(array("Save","class"=>"btn btn-dark")) ?>
    </div>
    </form>
</div>