<div id="widget_{{widget.id}}" class="{{parm['width']}}" >{{controls}}<div id="w_{{widget.id}}" style="width:100%;height:500px"><svg></svg></div><script>






(function() {
    
    var datain=[
{% for key,series in parm['db'] %}
{
     "key": '{{key|escape_js}}',
     "values": [
        {% for row in series %}
    {x:'{{ row['x_axis']|escape_js }}',y:{{ row['value']|escape_js }}} ,
        {% endfor  %}
]},

{% endfor  %}
];
    
                nv.addGraph(function() {
                    var chart = nv.models.lineChart()
                        .useInteractiveGuideline(true);

                    d3.select('#w_{{widget.id}} svg')
                        .datum(datain)
                        .transition().duration(500)
                        .call(chart);

                    nv.utils.windowResize(chart.update);

                    $('#w_{{widget.id}}').data('chart', chart);

                    return chart;
                });
            })();




</script>{{ content() }}</div>