  <div id="demo"></div>

  <script>

    var dataSet = [
<?php 
    
    $out = array();
    
      foreach ($data['db']['table1'] as $key => $subarr) 
      {
      $newarr=array();
            foreach($subarr as $sub_key=>$sub_value)
                                {
                                    $floatVal = floatval($sub_value);
                                    // If the parsing succeeded and the value is not equivalent to an int
                                    if($floatVal && intval($floatVal) != $floatVal)
                                    {
                                    $newarr[]= number_format ( $sub_value , 2 , "." , "," );
                                    }
                                    else
                                    {
                                    $newarr[]=$sub_value;
                                    }
                                }

      $out[]= "['".implode("','" , $newarr)."']";
      }
      echo implode(",",$out);
      ?>
    ];

    $(document).ready(function() {
    $('#demo').html( '<table cellpadding="0" cellspacing="0" border="0" class="display" id="example"></table>' );

    $('#example').dataTable( {
    "data": dataSet,
    "columns": [
    <?php 
    
    $out = array();
    
      foreach (array_keys($data['db']['table1']['0']) as $key) 
      {
      $out[]= "{ \"title\": \"".$key."\"}";
      }
      echo implode(",",$out);
      ?>

    ]
    } );
    } );

    $('#example tbody').on('click', 'tr', function () {
    var name = $('td', this).eq(0).text();
    update_dashboard("<?php echo $data['link']['table1'] ?>", name);
    } );

  </script>
