
                    <div class="ar-1-1">
                         <div class="widget-3 panel no-border no-margin widget-loader-bar" style="background-color:red">
                        <div class="panel-body no-padding">
                          <div class="metro live-tile" data-mode="carousel" data-start-now="true" data-delay="3000">
                            <div class="slide-front tiles slide active">
                              <div class="padding-30">
                           
                                <div class="pull-bottom p-b-30">
                                  <h3 class="no-margin text-white p-b-10">Revenue
                                                            <span class="semi-bold">25000</span>
                                                        </h3>
                                </div>
                              </div>
                            </div>
                            <div class="slide-back tiles">
                                <div class="padding-30">

                                    <div class="pull-bottom p-b-30">
                                        <h3 class="no-margin text-white p-b-10">
                                            Impressions
                                            <span class="semi-bold">2500077</span>
                                        </h3>
                                    </div>
                                </div>
                            </div>
                            <div class="slide-back tiles">
                                  <div class="padding-30">
                                      <div class="pull-bottom p-b-30">
                                          <p class="p-t-10 fs-12 p-b-5 hint-text">21 Jan</p>
                                          <h3 class="no-margin text-white p-b-10">
                                              Your Weekly Stats Are
                                              <br><span class="semi-bold">page</span>
                                          </h3>
                                      </div>
                                  </div>
                              </div>
                          </div>
                        </div>
                      </div>
                      </div>
                  <script>
$(".widget-3 .metro").liveTile();
</script>{{ content() }}