<div id="widget_{{widget.id}}" class=" m-b-10 {{parm['width']}} "  class="{{parm['width']}}" > {{controls}}
                    <div class="ar-1-1">
                         <div class="widget-3 panel no-border no-margin widget-loader-bar" style="background-color:{{parm['tile_color']}}">
                        <div class="panel-body no-padding">
                          <div class="metro live-tile" data-mode="carousel" data-start-now="true" data-delay="3000">

                  {% for key, value in parm['db']['0']['tiles'] %}
                  
                  <div class="slide-back tiles">
                                <div class="padding-30">

                                    <div class="pull-bottom p-b-30">
                                        <h3 class="no-margin text-white p-b-10">
                                            {{key|capitalize}}</h3>
                                            <h3 class="no-margin text-white p-b-10"><span class="semi-bold">{{value}}</span></h3>
                                        
                                    </div>
                                </div>
                            </div>
                  
                  {% endfor %}
                          </div>
                        </div>
                      </div>
                      </div>
                  <script>
$(".widget-3 .metro").liveTile();
</script>{{ content() }}</div>