<div id="widget_{{widget.id}}" class="col-md-{{parm['width']}} {{parm['width']}} "  class="{{parm['width']}}" > {{controls}}<div class="col-md-{{parm['width']}}">
<select id="w_{{widget.id}}" style="width:100%" class="input" multiple="multiple" placeholder="{{parm['title']}}">
     {% for entry in parm['db'] %}
      <option value="{{entry['values']}}">{{entry['values']}}</option>
    {% endfor  %}
</select>
</div><script>

$("#w_{{widget.id}}").select2();

        $("#w_{{widget.id}}").change(function() {
        
            update_dashboard("{{parm['link_table']}}","{{parm['target_link']}}","=", $("#w_{{widget.id}}").select2("val"),{{widget.id}});
  
        });



</script>{{ content() }}</div>