<div id="portlet_{{portlet.id}}"  style="height:100%" >     
            <div style="height:100%" >
              <div class="panel" >
                <div class="panel-header" style="background-color:{{parm['color']}}">
                  <h3>{{parm['title']}}</h3>
                </div>
                <div class="panel-content">
                 <div class="row">
                            {{region[0]}}
                            </div>
                 </div>
              </div>
            </div>
            
{{ content() }}</div>