    <section class="app">
        <aside class="aside-sm emails-list">
            <section>

                <ul class="nav nav-tabs text-right">
                    <li class="emails-action">
                        <i class="icon-rounded-arrow-curve-left"></i>
                        <i class=" icon-rounded-heart"></i>
                        <div class="pos-rel dis-inline">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" data-delay="300">
                                <i class=" icon-rounded-arrow-down-thin"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#" class="reorder-menu">Select All</a></li>
                                <li><a href="#" class="remove-menu">Not Read</a></li>
                                <li><a href="#" class="hide-top-sidebar">Read</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="active f-right"><a href="#recent" data-toggle="tab">Recent</a></li>
                    <li class="f-right"><a href="#alphabetically" data-toggle="tab">Alphabetically</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane fade" id="alphabetically">
                        <div class="messages-list withScroll show-scroll" data-padding="200" data-height="window">
                            <div class="message-item media">
                                <div class="media">
                                    <img src="../assets/global/images/avatars/avatar11_big.png" alt="avatar 3" width="40" class="sender-img">
                                    <div class="media-body">
                                        <div class="sender">Bobby Brown</div>
                                        <div class="email">bobby-brown@gmail.com</div>
                                    </div>
                                </div>
                            </div>
                            <div class="message-item media">
                                <div class="media">
                                    <img src="../assets/global/images/avatars/avatar8_big.png" alt="avatar 3" width="40" class="sender-img">
                                    <div class="media-body">
                                        <div class="sender">Bobby Hook</div>
                                        <div class="email">bobby-Hook@yahoo.com</div>
                                    </div>
                                </div>
                            </div>
                            <div class="message-item media">
                                <div class="media">
                                    <img src="../assets/global/images/avatars/avatar4_big.png" alt="avatar 3" width="40" class="sender-img">
                                    <div class="media-body">
                                        <div class="sender">John Snow</div>
                                        <div class="email">jsnow@msn.com</div>
                                    </div>
                                </div>
                            </div>
                            <div class="message-item media">
                                <div class="media">
                                    <img src="../assets/global/images/avatars/avatar6_big.png" alt="avatar 3" width="40" class="sender-img">
                                    <div class="media-body">
                                        <div class="sender">James Miller</div>
                                        <div class="email">james-miller@aol.com</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade in active" id="recent">
                        <div class="messages-list withScroll show-scroll" data-padding="200" data-height="window">
                            <div class="message-item media">
                                <div class="media">
                                    <img src="../assets/global/images/avatars/avatar4_big.png" alt="avatar 3" width="40" class="sender-img">
                                    <div class="media-body">
                                        <div class="sender">John Snow</div>
                                        <div class="email">j-snow@yahoo.com</div>
                                    </div>
                                </div>
                            </div>
                            <div class="message-item media">
                                <div class="media">
                                    <img src="../assets/global/images/avatars/avatar3_big.png" alt="avatar 3" width="40" class="sender-img">
                                    <div class="media-body">
                                        <div class="sender">Sarah Higgle</div>
                                        <div class="email">s-higgle@gmail.com</div>
                                    </div>
                                </div>
                            </div>
                            <div class="message-item media">
                                <div class="media">
                                    <img src="../assets/global/images/avatars/avatar6_big.png" alt="avatar 3" width="40" class="sender-img">
                                    <div class="media-body">
                                        <div class="sender">James Miller</div>
                                        <div class="email">j-miller@hotmail.com</div>
                                    </div>
                                </div>
                            </div>
                            <div class="message-item media">
                                <div class="media">
                                    <img src="../assets/global/images/avatars/avatar7_big.png" alt="avatar 3" width="40" class="sender-img">
                                    <div class="media-body">
                                        <div class="sender">Martin Descker</div>
                                        <div class="email">m-descker@yahoo.com</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </aside>
        <div class="email-details">
            <section>
                <div class="email-subject">
                    <h1><strong>Process</strong> Results</h1>
                    <div class="clearfix">
                        <p>from <strong><span class="sender">Me</span></strong> &bull; <span class="date-send"></span></p>
                        <div class="pos-rel pull-left">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" data-delay="300">
                                <i class=" icon-rounded-arrow-down-thin"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#" class="reorder-menu">Delete email</a></li>
                                <li><a href="#" class="remove-menu">Move</a></li>
                                <li><a href="#" class="hide-top-sidebar">Print</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="email-details-inner withScroll" data-height="window" data-padding="200">

                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>First Name</th>
                                            <th>Last Name</th>
                                            <th>Username</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>1</td>
                                            <td>Mark</td>
                                            <td>Otto</td>
                                            <td>@mdo</td>
                                        </tr>
                                        <tr>
                                            <td>2</td>
                                            <td>Jacob</td>
                                            <td>Thornton</td>
                                            <td>@fat</td>
                                        </tr>
                                        <tr>
                                            <td>3</td>
                                            <td>Larry</td>
                                            <td>the Bird</td>
                                            <td>@twitter</td>
                                        </tr>
                                        <tr>
                                            <td>4</td>
                                            <td>Steve</td>
                                            <td>Mac Queen</td>
                                            <td>@steve</td>
                                        </tr>
                                    </tbody>
                                </table>

                </div>
            </section>
        </div>
    </section>
