<div class="modal-content">

  <?php echo $this->getContent(); ?>
  <?php echo $this->tag->form("users/create") ?>


  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <br>
      <i class="fa fa-user fa-7x"></i>
      <h4 id="myModalLabel" class="semi-bold">Create New User.</h4>
      <p class="no-margin">Please provide all the required information. </p>
      <br>
 </div>
  <div class="modal-body">
    <div class="row form-row">
      <div class="col-md-6">
        <label class="form-label">Full Name</label>
        <?php echo $this->tag->textField(array("full_name", "class" => "form-control")) ?>
      </div>
      <div class="col-md-6">
        <label class="form-label">Phone Number</label>
        <?php echo $this->tag->textField(array("phone_number", "class" => "form-control")) ?>
      </div>
    </div>

      <div class="row form-row">
      <div class="col-md-4">
        <label class="form-label">Email</label>
        <?php echo $this->tag->textField(array("email", "class" => "form-control")) ?>
      </div>

      <div class="col-md-4">
        <label class="form-label">Password</label>
        <?php echo $this->tag->passwordField(array("password", "class" => "form-control")) ?>
      </div>

        <div class="col-md-4">
          <label class="form-label">Role</label>
          <?php echo $this->tag->selectStatic(array("role", "class" => "form-control"), array("User" => "User", "Supervisor" => "Supervisor")) ?>
        </div>
      </div>

    </div>


  <div class="modal-footer">
    <?php echo $this->tag->hiddenField("image_path") ?>
    <?php echo $this->tag->hiddenField("status") ?>
    <?php echo $this->tag->hiddenField("organisation_id") ?>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <?php echo $this->tag->submitButton(array("Save","class"=>"btn btn-primary")) ?>

  </div>

  </form>
</div>