<h3>
  <?php echo $data['parm']['title']?>
</h3>

<select id="<?php echo "w_".$widget->id?>" style="width:100%">
      <?php 
      foreach ($data['db']['table1'] as $entry) {
      echo '<option value="'.$entry['widget_link_column'].'">'.$entry['values'].'</option>';
      }
      ?>
</select>
</br>
</br>

<script>
  
    $( document ).ready(function() {
  
        $("#<?php echo "w_".$widget->id ?>" ).change(function() {

            update_dashboard("<?php echo $data['link']['table1'] ?>", this.value);
  
        });

        $("#<?php echo "w_".$widget->id ?>" ).change();

    });

</script>