<div id="portlet_{{portlet.id}}" class="{{parm['width']}}" > 
							<div class="met_title">
								<h2>{{parm['title']}}</h2>
							</div>

							<div class="met_skills">
                            <div class="row">
                            {{region[0]}}
                            </div>
                            <div class="row">
                            {{region[1]}}
                            </div>
                            <div class="row">
                            {{region[2]}}
                            </div>
							</div>
						{{ content() }}</div>