
<?php echo $this->tag->form("payment_method/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("payment_method", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create payment_method</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="company_registered_name">Company Of Registered Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("company_registered_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="registration_number">Registration Of Number</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("registration_number", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="vat_number">Vat Of Number</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("vat_number", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="payment_method">Payment Of Method</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("payment_method")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="billing_contact">Billing Of Contact</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("billing_contact", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="organisation_id">Organisation</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("organisation_id", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
