<div class="col-md-12 portlets">
    <div class="panel">
        <div class="panel-header">
            <h3><i class="fa fa-table"></i> <strong>Logins</strong></h3>
            <div class="control-btn">
                <a href="#" class="panel-reload hidden"><i class="icon-reload"></i></a>
                <a class="hidden" id="dropdownMenu1" data-toggle="dropdown">
                    <i class="icon-settings"></i>
                </a>
                <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="dropdownMenu1">
                    <li>
                        <a href="#">Action</a>
                    </li>
                    <li>
                        <a href="#">Another action</a>
                    </li>
                    <li>
                        <a href="#">Something else here</a>
                    </li>
                </ul>
                <a href="#" class="panel-popout hidden tt" title="Pop Out/In"><i class="icons-office-58"></i></a>
                <a href="#" class="panel-maximize hidden"><i class="icon-size-fullscreen"></i></a>
                <a href="#" class="panel-toggle"><i class="fa fa-angle-down"></i></a>
                <a href="#" class="panel-close"><i class="icon-trash"></i></a>
            </div>
        </div>
        <div class="panel-content">
            <div class="row column-seperation">
                <div class="col-md-4">
                    <h3>Create New Login Page</h3>
                    <p>Please select one of the login templates below.</p>
                    <div class="grid-body no-border">
                        {%for login in loginList %}
                        <div class="alert bg-primary">
                            <div data-type="'.$type.'" class="Data_Connector heading" onClick="create_new('login','{{login}}')">{{login}}</div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
                <div class="col-md-8" style="min-height:500px;">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th style="width:20%">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($logins as $login) { ?>
                            <tr>
                                <td>
                                    <?php echo $login->name ?>
                                </td>
                                <td>
                                    <?php echo $this->tag->linkTo(array("logins/".$login->type."/edit/" . $login->id, "Edit",'class'=>"btn btn-success btn-xs btn-small")); ?>
                                    <?php echo $this->tag->linkTo(array("logins/delete/" . $login->id, "Delete",'class'=>"btn btn-danger btn-xs btn-small")); ?>
                                </td>
                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>


<?php echo $this->getContent() ?>


