
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("physical_address/new", "Create physical_address")) ?>
</div>

<?php echo $this->tag->form(array("physical_address/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search physical_address</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="country">Country</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("country", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="state">State</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("state", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="city">City</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("city", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="street">Street</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("street", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="organisation_id">Organisation</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("organisation_id", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
