<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("physical_address/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("physical_address/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Country</th>
            <th>State</th>
            <th>City</th>
            <th>Street</th>
            <th>Organisation</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $physical_addres) { ?>
        <tr>
            <td><?php echo $physical_addres->id ?></td>
            <td><?php echo $physical_addres->country ?></td>
            <td><?php echo $physical_addres->state ?></td>
            <td><?php echo $physical_addres->city ?></td>
            <td><?php echo $physical_addres->street ?></td>
            <td><?php echo $physical_addres->organisation_id ?></td>
            <td><?php echo $this->tag->linkTo(array("physical_address/edit/" . $physical_addres->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("physical_address/delete/" . $physical_addres->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("physical_address/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("physical_address/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("physical_address/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("physical_address/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
