<div id="widget_{{widget.id}}" class="{{parm['width']}}" >{{controls}}
<div id="w_{{widget.id}}" style="width:100% min-width: 600px; height: 450px; margin: 0 auto"></div>
<script>
$('#w_{{widget.id}}').highcharts({
            chart: {
            type: '{{parm['chart_type']}}',
            spacingBottom: 50,
            spacingTop: 50,
            spacingLeft: 50,
            spacingRight: 50,
            events: {
            selection: function(event) {
                for (var i = 0; i < this.series[0].data.length; i++) {
                    var point = this.series[0].data[i];
                    if (point.x > event.xAxis[0].min &&
                        point.x < event.xAxis[0].max &&
                        point.y > event.yAxis[0].min &&
                        point.y < event.yAxis[0].max) {
                            point.select(true, true);
                        }
                    
                }
                return false;
            }
        },
			zoomType: 'xy'
        },
        plotOptions: {
            series: {
                allowPointSelect: true
            }
        },
 title: {
            text: '{{parm['chart_title']}}'
        },
        		  credits: {
  enabled: false
  },
        xAxis: {
            title: {
                text: '{{parm['x_label']}}'
            },
            
                {% if parm['xtype'] == "Date" %}
                type: 'datetime',
                {% elseif parm['xtype'] == "Category" %}
                type: 'datetime',
                {% else %}
                {% endif  %}
            
        },
        yAxis: {
            title: {
                text: '{{parm['y_label']}}'
            }
        },
        colors:{{parm['colors']}},
 series: [
{% for key,series in parm['db'] %}
{
     name: '{{key|escape_js}}',
     data: [
        {% for row in series %}
        
                {% if parm['xtype'] == "Date" %}
    [Date.parse('{{ row['x_axis']|escape_js }}'),{{ row['value']|escape_js }}] ,
                {% elseif parm['xtype'] == "Category" %}
    ['{{ row['x_axis']|escape_js }}',{{ row['value']|escape_js }}] ,
                {% else %}
    [{{ row['x_axis']|escape_js }},{{ row['value']|escape_js }}] ,
                {% endif  %}
        {% endfor  %}
]},

{% endfor  %}
]

});

$('#preview_{{widget.id}}').on('click', function(){
    
            var chart = $('#w_{{widget.id}}').highcharts(),
            selectedPoints = chart.getSelectedPoints();

                            var temp=[];
                        $.each(selectedPoints, function (i, value) {
                            temp.push(value.x);
                        });
                            update_dashboard("{{parm['target_link']}}", temp,{{widget.id}});
    
});


</script>{{ content() }}</div>