  <div class="col-md-{{parm['width']}}">
                    <div class="panel panel-default">
                      <div class="panel-heading separator">
                        <div class="panel-title">{{parm['title']}}
                        </div>
                      </div>
                      <div class="panel-body">
                      {{region[0]}}
                      </div>
                    </div>
                  </div>{{ content() }}