<div id="portlet_{{portlet.id}}"class="col-md-{{parm['width']}}" > 
                    <div class="panel panel-default">
                      <div class="panel-heading separator">
                        <div class="panel-title">{{parm['title']}}
                        </div>
                      </div>
                      <div class="panel-body" style="height: inherit;">
                          <div class="col-md-12">
                      {{region[0]}}
                      </div>
 <div class="col-md-12">
                      {{region[1]}}
                      </div>
                       <div class="col-md-12">
                      {{region[2]}}
                      </div>
                      </div>
                    </div>
                  {{ content() }}</div>