<div id="widget_{{widget.id}}"  class="{{parm['width']}}" > {{controls}}
<style>
#w_{{widget.id}} .ui-selecting { background: #FECA40; }
  #w_{{widget.id}} .ui-selected { background: #F39814; color: white; }
</style><div>
<nav style="max-height:400px; overflow: auto; overflow-x: hidden;">
				<ul id="w_{{widget.id}}" class="met_clean_list sf-js-enabled sf-arrows">
				    
				    {% for entry in parm['db'] %}
				    <li data-link="{{entry['link_column']}}"><a>{{entry['value']}}</a></li>
{% endfor  %}
				</ul>
			</nav>
			</div>
  
  <script>
  $(function() {
    $( "#w_{{widget.id}}" ).selectable({
      stop: function() {
        var link_set=[];
        $( "li.ui-selected", this ).each(function() {
            link_set.push($(this).data('link'));
        });
        
     update_dashboard("{{parm['target_link']}}", link_set,{{widget.id}});
        
        
      }
    });
  });
  </script>
  
{{ content() }}</div>