<div id="portlet_{{portlet.id}}" class="{{parm['width']}}" >     
            <div >
              <div class="panel" >
                <div class="panel-content">
                 <div class="row">
                            {{region[0]}}
                            </div>
                            <div class="row">
                            {{region[1]}}
                            </div>
                            <div class="row">
                            {{region[2]}}
                            </div>
                 </div>
                 <div class="panel-footer" style="background-color:{{parm['color']}}">
                  <h3>{{parm['title']}}</h3>
                </div>
              </div>
            </div>
            
{{ content() }}</div>