<div id="widget_{{widget.id}}"   > {{controls}}<div>
    
<h3>
  {{parm['title']}}
</h3>

<select id="w_{{widget.id}}" class="input form-control">
     {% for entry in parm['db'] %}
      <option value="{{entry['values']}}">{{entry['values']}}</option>
    {% endfor  %}
      
</select>


</div><script>

        $("#w_{{widget.id}}").change(function() {

            update_dashboard("{{parm['link_table']}}","{{parm['target_link']}}","=", this.value,{{widget.id}});
  
        });
        
        function submit_{{widget.id}}(multiple)
        {
            return $("#w_{{widget.id}}").val();
        }

</script>{{ content() }}</div>