
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("database/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("database", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit database</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="db_host">Db Of Host</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("db_host", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="db_username">Db Of Username</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("db_username", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="db_password">Db Of Password</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("db_password", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="db_name">Db Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("db_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="organisation_id">Organisation</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("organisation_id", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
