<h4> <?php echo $data['parm']['title'] ?> </h4>
<div id="<?php echo "widget_".$widget->id ?>" >
</div>

<script>

  var widget_id = <?php echo $widget->id?>;

  var myList= <?php echo json_encode($data['db']['mc_table1']) ?>;

  var y_key = [];

  for (var i = 0 ; i < myList.length ; i++) {
        var rowHash = myList[i];
        for (var key in rowHash) {
            if ($.inArray(key, y_key) == -1){
                y_key.push(key);
    }
    }
    }

	var x_key=y_key.splice(0, 1);
	
Morris.Line({
  element: '<?php echo "widget_".$widget->id ?>',
  data: myList,
  xkey: x_key,
  ykeys: y_key,
  labels: y_key,
  lineWidth:'1',
  fillOpacity: '1.0',
  grid:'false',
  });

</script>





