  <div class="placeholder-container">
    <div class="placeholder">
      <div class="placeholder-content ui-droppable">
        <div class="placeholder-content-area">
          
          <?php echo $this->getContent() ?>          
          
        </div>
      </div>
    </div>
    <div class="placeholder-handle">
      <div class="handle-move" data-rel="tooltip" data-placement="right" data-original-title="Move">
        <i class="fa fa-bars"></i>
      </div>
      <div class="handle-remove" data-rel="tooltip" data-placement="right" data-original-title="Remove">
        <i class="fa fa-times"></i>
      </div>
    </div>
  </div>