<link rel="stylesheet" href="/assets/plugins/sinister/sinister.css">
  <link href="/assets/plugins/bootstrap-tag/bootstrap-tagsinput.min.css" rel="stylesheet">
    <link href="/assets/plugins/bootstrap-select2/select2.css" rel="stylesheet" type="text/css" media="screen"/>
    <link href="/assets/css/style.css" rel="stylesheet" type="text/css"/>

    <script>
      var links =<?php echo json_encode($links)?>;
    </script>

    <ul class="breadcrumb">
      <li>
        <p>YOU ARE HERE</p>
      </li>
      <li>
        <a href="#" class="active">Edit Dashboard</a>
      </li>
    </ul>
    <div class="page-title">
      <a href="/organisation/edit/"
        <?php echo $organisation_id ?>">
        <i  class="icon-custom-left"></i>
      </a>
      <h3>
        Edit - <span class="semi-bold">Dashboard</span>
      </h3>
    </div>

    <link href="/assets/plugins/icon-picker/css/fontawesome-iconpicker.min.css" rel="stylesheet">

      <link href="/assets/plugins/page-builder/css/style.css" rel="stylesheet"></link>

      <div class="row-fluid">
        <div class="col-md-12">
          <div id="page-builder" >
            <ul class="nav nav-tabs">
              <li class="width-16p active">
                <a href="#info" data-toggle="tab">
                  <span class="text-center">Basic Info</span>
                </a>
              </li>
              <li class="width-16p">
                <a href="#layout" data-toggle="tab">
                  <span class="text-center">Layout</span>
                </a>
              </li>

              <?php  
            
    $directory = '../app/widgets/'.$theme.'/';

    //get all files in specified directory
    $files = glob($directory . "*", GLOB_BRACE);
    
    //print each file name
    foreach($files as $file)
    {
    //check to see if the file is a folder/directory
    if(is_dir($file))
    {
    echo '<li class="width-16p"><a href="#'.basename($file).'" data-toggle="tab"><span class="text-center">'.ucwords (basename($file)).'</span></a></li>';
    }
    }
   
    ?>
            </ul>
            <div class="tab-content clearfix" style="overflow:visible">
              <div class="tab-pane fade in active" id="info">
                <?php echo $this->tag->form("dashboard/save") ?>
                <div class="row column-seperation">
                  <div class="col-md-6">
                    <h4>Menu Settings</h4>
                    <div class="row">

                      <div class="form-group col-md-7">
                        <label class="form-label">Title</label>
                        <span class="help">e.g. "Market Metrics"</span>
                        <div class="input-with-icon  right">
                          <i class=""></i>
                          <?php echo $this->tag->textField(array("title", "class" => "form-control")) ?>
                        </div>
                      </div>

                      <div class="form-group col-md-5">
                        <label class="form-label">Menu Weight</label>
                        <span class="help">e.g. "Please Select"</span>
                        <div class="input-with-icon  right">
                          <i class=""></i>
                          <?php echo $this->tag->textField(array("weight", "class" => "form-control")) ?>
                        </div>
                      </div>

                    </div>

                    <div class="row">
                      <div class="form-group col-md-7">
                        <label class="form-label">Icon</label>
                        <span class="help">e.g. "Please Select"</span>
                        <div class="input-group">
                          <?php echo $this->tag->textField(array("icon", "class"=>"form-control icp icp-auto","data-placement"=>"bottomRight")) ?>
                          <span class="input-group-addon"></span>
                        </div>
                      </div>

                      <div class="form-group col-md-5">
                        <label class="form-label">Style</label>
                        <span class="help">e.g. "Please Select"</span>
                        <div class="input">
                          <select class="form-control" name="style">

                            <?php  
            echo $theme;
            
  //path to directory to scan
    $directory = "../app/themes/".$theme."/layouts/";

    //get all files in specified directory
    $files = glob($directory . "*.{phtml}", GLOB_BRACE);
    
    //print each file name
    foreach($files as $file)
    {
    $type = str_replace(".phtml","",basename($file));
    echo '<option value="'.$type.'" >'.ucwords($type).'</option>';
    }
   
    ?>
                          </select>
                        </div>
                      </div>
                    </div>
                    <?php echo $this->tag->hiddenField("organisation_id") ?>
                    <?php echo $this->tag->hiddenField("id") ?>
                  </div>

                  <div class="col-md-6">
                    <h4>Dashboard Links</h4>
                    <div class="row">

                      <div class="form-group col-md-5">
                        <label class="form-label">Name</label>
                        <span class="help">e.g. "Please Select"</span>
                        <div style="width:100%">
                          <input type="text" id="link_value" style="width:100%"></input>
                        </div>
                      </div>

                      <div class="form-group col-md-5">
                        <label class="form-label">Defaul Value</label>
                        <span class="help">e.g. "Please Select"</span>
                        <div style="width:100%">
                          <input type="text" id="link_text" style="width:100%"></input>
                        </div>
                      </div>

                      <div class="form-group col-md-2 ">
                        <label class="form-label">
                          </br>
                        </label>
                        <span class="help">
                          </br>
                        </span>
                        <div class= "pull-right">
                          <button class="add_field_button btn btn-default ">
                            <i class="fa fa-plus"></i>&nbsp;&nbsp;<span >Add Link</span>
                          </button>
                        </div>
                      </div>
                    </div>

                    <div class="row">
                      <div class="form-group col-md-12">
                        <label class="form-label">Links</label>
                        <span class="help">e.g. "Please Select"</span>
                        <div style="width:100%">
                          <input id="links-input" class="bootstrap-tagsinput" type="text" />
                        </div>
                      </div>

                      <?php echo $this->tag->hiddenField("links") ?>

                    </div>
                  </div>
                </div>


                <p class="pull-right">
                  <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-success btn-cons")) ?>
                  <button type="button" class="btn btn-white btn-cons">Cancel</button>
                </p>
                </form>
              </div>
              <div class="tab-pane fade" id="layout">

                <div data-type="row" class="drag">
                  <p>
                    <strong>New Row</strong>
                  </p>
                  <p>100%</p>
                </div>

                <div data-type="canvas" class="drag">
                  <p>
                    <strong>New Canvas</strong>
                  </p>
                </div>

              </div>

              <?php  
  //path to directory to scan
    $directory = '../app/widgets/'.$theme.'/';

    //get all files in specified directory
    $files = glob($directory . "*", GLOB_BRACE);
    

    //print each file name
    foreach($files as $file)
    {
    //check to see if the file is a folder/directory
    if(is_dir($file))
    {
    echo '<div class="tab-pane fade" id="'.basename($file).'">';  
    $subdirectory = '../app/widgets/'.$theme.'/'.basename($file).'/';
    //get all files in specified directory
    $subfiles = glob($subdirectory."*.{php}", GLOB_BRACE);  
    
        foreach($subfiles as $subfile)
    {
    $type = str_replace("Controller.php","",basename($subfile));
    $name = trim(implode(' ', preg_split('/(?=\p{Lu})/u', $type)));
    $type= "w_".basename($file)."/".strtolower(str_replace(" ","_",$name)) ;

    echo '<div data-type="'.$type.'" class="drag">'.$name.'</div>';
    
  }  
  echo '</div>';
   
    }
    }
   
    ?>
            </div>


            <div class="builder-wrapper">

<?php $this->getContent(); ?>

            </div>


          </div>
        </div>
      </div>


      <!-- Modal -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog"  id="modal">
          <div id="modal_content"></div>
        </div>
        <!-- /.modal-dialog -->
      </div>
      <!-- /.modal -->


      <script src='/assets/plugins/jquery-ui/jquery_and_jqueryui.js'></script>
      <script src='/assets/plugins/bootstrap-tag/bootstrap-tagsinput.min.js'></script>

      <script src="/assets/plugins/icon-picker/js/fontawesome-iconpicker.js"></script>
      <script src="/assets/js/tabs_accordian.js" type="text/javascript"></script>
      <script src="/assets/plugins/bootstrap-select2/select2.js" type="text/javascript"></script>

      <script>

        var $j = jQuery.noConflict();

        var dataIn;
        $.getJSON("/widget/getAllTables", function(data){
        $j("#link_value").select2({
        data:data,
        placeholder: "Select a Linking Column"
        });
        });

        var data= <?php echo $links ?>;
        var elt = $j('#links-input');
        elt.tagsinput({
        itemValue: 'value',
        itemText: 'label',
        });

        if(data!=null){
        $.each(data, function(i, item) {
        elt.tagsinput('add', { "value": data[i].text , "text": data[i].default,"label": "Database Table = "+data[i].table + ": Column = " + data[i].column + ": Value = " + data[i].default  });
        });
        }

        var max_fields      = 10; //maximum input boxes allowed
        var add_button      = $(".add_field_button"); //Add button ID

        var x = 1; //initlal text box count
        $(add_button).click(function(e){ //on add input button click
        e.preventDefault();
        if(x < max_fields){ //max input box allowed
            x++; //text box increment
            elt.tagsinput('add', { "value": $("#link_value").val(), "text": $("#link_text").val(),"label": $("#link_value").val()+ " = " +$("#link_text").val() });
            
        $("#link_value").val("");
        $("#link_text").val("");
        
        elt.tagsinput('items');
        
        var links_ar = $.map(elt.tagsinput('items'), function (obj) {
        var link=JSON.parse(obj.value);
        return {
        table:  link['table'],
        column: link['column'],
        default: obj.text,
        text: obj.value,
        id: obj.value
    };
});

        document.getElementsByName("links")[0].value =   JSON.stringify(links_ar);
      };
      });
       
        
  elt.on('itemRemoved', function(event) {

        var links_ar = $.map(elt.tagsinput('items'), function (obj) {
        var link=JSON.parse(obj.value);
        return {
        table:  link['table'],
        column: link['column'],
        default: obj.text,
        text: obj.value,
        id: obj.value
    };
});
        document.getElementsByName("links")[0].value =   JSON.stringify(links_ar);
});
      
      $j('.icp-auto').iconpicker();

      <?php foreach ($canvas as $canvasItem) { ?>
        $("div").find("[data-rowNumber='<?php echo $canvasItem->row ?>']").append( $('<div></div>').load("/Canvas/render/<?php echo $canvasItem->id ?>/builder", function(){
        updatedropzonecanvas();
        }));
        <?php } ?>

        $j('.drag').draggable({
        appendTo: 'body',
        zIndex: 100,
        helper: "clone"
        });

        $j('.dropzone-row').droppable({
        activeClass: 'active', greedy: true,
        hoverClass: 'hover',
        tolerance: "pointer",
        accept: ":not(.ui-sortable-helper)", // Reject clones generated by sortable
        drop: function (e, ui) {

        var rowNumber = $(this).attr("data-rowNumber");
        var columnNumber = $(this).children().length;

        var draggable = ui.draggable;
        var datatype = draggable.attr("data-type");

        switch (datatype) {
        case "canvas":
        $("#modal_content").load("/Canvas/new/<?php echo $dashboard_id ?>" + "/" + rowNumber + "/" + columnNumber, function () {
        $("#myModal").modal("show");
        });
        break;
        }
        }
        })

        function updatedropzonecanvas(){

        $j('.widget_drag').draggable({
        handle: ".draghandle",
        appendTo: 'body',
        zIndex: 100,
        helper: "clone"
        });


        $j('.dropzone-canvas').droppable({
        activeClass: 'active', greedy: true,
        hoverClass: 'hover',
        tolerance: "pointer",
        accept: ":not(.ui-sortable-helper)", // Reject clones generated by sortable
        drop: function (e, ui) {
        var draggable = ui.draggable;
        var datatype = draggable.attr("data-type");


        var canvasId = $(this).attr("data-canvasId");
        var rowNumber = $(this).attr("data-canvasRowNumber");
        var columnNumber = $(this).children().length;

        if(datatype.substr(0, 2)=="u_")
        {

        $("#modal_content").load("/widget/move/"+ canvasId + "/" + rowNumber + "/" + columnNumber + "/" + draggable.attr("data-widget_id") , function () {
        $("#myModal").modal("show");
        });
        }

        else if(datatype.substr(0, 2)=="w_")
        {
        $("#modal_content").load("/widgets/"+datatype.substring(2)+"/new/"+ canvasId + "/" + rowNumber + "/" + columnNumber, function () {
        $("#myModal").modal("show");
        });
        }
        }
        });
        };

        function canvas_edit(id){
        $("#modal_content").load("/canvas/edit/" + id, function () {
        $("#myModal").modal("show");
        })};

        function canvas_delete(id){
        $("#modal_content").load("/canvas/delete/" + id, function () {
        $("#myModal").modal("show");
        })};

        function widget_edit(type,id){
        $("#modal_content").load("/widgets/"+type.trim()+"/edit/" + id, function () {
        $("#myModal").modal("show");
        })};

        function widget_delete(id){
        $("#modal_content").load("/widget/delete/" + id, function () {
        $("#myModal").modal("show");
        })};

      </script>
    